import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Viewer from "../components/Viewer";

const Home: NextPage = () => {
  const [scene, setScene] = useState("intro");
  const [t, setT] = useState([
    {
      onclick: () => {
        setScene("elaiourgeio");
      },
      id: "marker-rfqd2q2h668",
      polygonRad: [
        [6.01, 0.356],
        [0.356, 0.325],
        [0.36, -0.295],
        [6.029, -0.359],
      ],
      svgStyle: {
        fill: "#ffff0045",
        stroke: "#00000000",
        strokeWidth: 2,
      },
    },
  ]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Viewer scene={scene} markers={t} />
    </div>
  );
};

export default Home;
